print("nu skal i tælle vores komponenter")
print("plus:", 2+2)
print("minus:", 2-2)
print("gange:", 2*3)
print("dividere:", 6/2)
print("'procent' dette er monolog. Tager rest værdien efter at have divideret. HVis det er muligt:", 100 % 10)
print("større end:", 5>3)
print("mindre end:", 5<3)
print("større end eller lig med:", 3>=3, 4>=3, 2>=3)
print("mindre end eller lig med:", 3<=3, 4<=3, 2<=3)
print("exponenter:", 2**5)
